services:
  ldapxls:
    image: joergmschulz/ldapusersgroups:latest
    build: 
      context: .
    container_name: ldapxls
    hostname: ldapxls
    
    environment:
      - DEBUG_DEVELOP=false
      
      - LDAPXLS_SEARCHBASE=${MM3SYNC_SEARCHBASE}
      - LDAPXLS_SEARCH_FILTER=${LDAPXLS_SEARCH_FILTER}
      - DOMAIN=${DOMAIN}
      - LDAP_USER=${LDAP_ADMIN_DN}
      - LDAP_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_HOSTNAME=${LDAP_HOSTNAME}
      - LDAPXLS_PREFERRED_LANGUAGE=${LDAPXLS_PREFERRED_LANGUAGE:-de}
      - NC_USER=${NC_USER}
      - NC_PASS=${NC_PASS}
      - NC_URL=${NC_URL}
      - OUTPUTFILE=${LDAPXLS_USERSGROUPS}
      - NCDIR=${USERDOCDIR}
      - LDAPXLS_ROTATION=${LDAPXLS_ROTATION:-0}
      

      
    networks:
      services:
        ipv4_address: ${LDAPXLS_IP}

  copyNcFiles:
    image: joergmschulz/copyncfiles:latest
    build: 
      context: .
      dockerfile: Dockerfile.copyNcFiles
    container_name: copyNcFiles
    hostname: copyNcFiles
    
    environment:
      - DEBUG_DEVELOP=true
      # source
      - C_USER=${C_USER}
      - C_PASS=${C_PASS}
      - C_URL=${C_URL}
      # target
      - NC_USER=${NC_USER}
      - NC_PASS=${NC_PASS}
      - NC_URL=${NC_URL}

      
    networks:
      services:
        ipv4_address: ${LDAPXLS_IP}






networks:
  services: 
    external: true
